<?php

namespace Telemon\Models;

/**
 * Telegram Message object
 *
 * @method int messageId()
 * @method int messageThreadId()
 * @method User from()
 * @method Chat senderChat()
 * @method int date()
 * @method Chat chat()
 * @method User forwardFrom()
 * @method Chat forwardFromChat()
 * @method int forwardFromMessageId()
 * @method string forwardSignature()
 * @method string forwardSenderName()
 * @method int forwardDate()
 * @method bool isTopicMessage()
 * @method Message replyToMessage()
 * @method User viaBot()
 * @method int editDate()
 * @method string mediaGroupId()
 * @method string authorSignature()
 * @method string text()
 * @method Entity[] entities()
 * @method Animation animation()
 * @method Audio audio()
 * @method Document document()
 * @method PhotoSize[] photo()
 * @method Sticker[] sticker()
 * @method Video video()
 * @method VideoNote videoNote()
 * @method Voice voice()
 * @method string caption()
 * @method CaptionEntities[] captionEntities()
 * @method Contact contact()
 * @method Dice dice()
 * @method Game game()
 * @method Poll poll()
 * @method Venue venue()
 * @method Location location()
 * @method User[] newChatMembers()
 * @method User leftChatMember()
 * @method string newChatTitle()
 * @method array newChatPhoto()
 * @method bool deleteChatPhoto()
 * @method bool groupChatCreated()
 * @method bool supergroupChatCreated()
 * @method bool channelChatCreated()
 * @method Message messageAutoDeleteTimerChanged()
 * @method int migrateToChatId()
 * @method int migrateFromChatId()
 * @method Message pinnedMessage()
 * @method Invoice invoice()
 * @method SuccessfulPayment successfulPayment()
 * @method string connectedWebsite()
 * @method PassportData passportData()
 * @method ProximityAlertTriggered proximityAlertTriggered()
 * @method ForumTopicCreated forumTopicCreated()
 * @method ForumTopicClosed forumTopicClosed()
 * @method ForumTopicEdited forumTopicEdited()
 * @method GeneralForumTopicHidden generalForumTopicHidden()
 * @method GeneralForumTopicUnhidden generalForumTopicUnhidden()
 * @method VideoChatScheduled videoChatScheduled()
 * @method VideoChatStarted videoChatStarted()
 * @method VideoChatEnded videoChatEnded()
 * @method VideoChatParticipantsInvited videoChatParticipantsInvited()
 * @method WebAppData webAppData()
 * @method InlineKeyboardMarkup replyMarkup()
 */
class Message extends BaseModel {}